insert into District (name, id_city) values ('Stare Miasto', '154');
insert into District (name, id_city) values ('Grzegórzki', '154');
insert into District (name, id_city) values ('Prądnik Czerwony', '154');
insert into District (name, id_city) values ('Prądnik Biały', '154');
insert into District (name, id_city) values ('Krowodrza', '154');
insert into District (name, id_city) values ('Bronowice', '154');
insert into District (name, id_city) values ('Zwierzyniec', '154');
insert into District (name, id_city) values ('Dębniki', '154');
insert into District (name, id_city) values ('Łagiewniki-Borek Fałęcki', '154');
insert into District (name, id_city) values ('Swoszowice', '154');
insert into District (name, id_city) values ('Podgórze Duchackie', '154');
insert into District (name, id_city) values ('Bieżanów-Prokocim', '154');
insert into District (name, id_city) values ('Podgórze', '154');
insert into District (name, id_city) values ('Czyżyny', '154');
insert into District (name, id_city) values ('Mistrzejowice', '154');
insert into District (name, id_city) values ('Bieńczyce', '154');
insert into District (name, id_city) values ('Wzgórza Krzesławickie', '154');
insert into District (name, id_city) values ('Nowa Huta', '154');